# Generated by Django 5.2.4 on 2025-07-22 11:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('initial_balance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('money_secured', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='LedgerNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('ledger_timeframe', models.CharField(choices=[('All', 'All'), ('Date Range', 'Date Range'), ('Yearly', 'Yearly'), ('Monthly', 'Monthly'), ('Weekly', 'Weekly'), ('Daily', 'Daily')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_open', models.DateTimeField()),
                ('date_closed', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=10)),
                ('position', models.CharField(choices=[('Short', 'Short'), ('Long', 'Long')], max_length=10)),
                ('timeframe', models.CharField(choices=[('1w', '1w'), ('1d', '1d'), ('4h', '4h'), ('2h', '2h'), ('1h', '1h'), ('30m', '30m'), ('15m', '15m'), ('5m', '5m')], max_length=10)),
                ('entry_price', models.FloatField()),
                ('trade_size', models.FloatField()),
                ('trade_total_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('exit_price', models.FloatField(blank=True, null=True)),
                ('initial_stop_loss', models.FloatField()),
                ('initial_tp', models.FloatField(blank=True, null=True)),
                ('commission_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pl', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('risk', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='')),
                ('account_balance_post_trade', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.accounts')),
            ],
        ),
        migrations.CreateModel(
            name='TradeSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('type', models.CharField(choices=[('Trailing Stop', 'Trailing Stop'), ('Entry', 'Entry'), ('Scale In', 'Scale In'), ('Scale Out', 'Scale Out'), ('Stopped Out', 'Stopped Out'), ('Take Profit', 'Take Profit')], max_length=15)),
                ('market_price', models.FloatField()),
                ('current_trade_size', models.FloatField()),
                ('current_pl', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('trade_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.trades')),
            ],
        ),
    ]
