# Generated by Django 5.2.4 on 2025-07-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trades',
            name='symbol',
            field=models.CharField(default='BTC', max_length=10),
            preserve_default=False,
        ),
    ]
