# Generated by Django 5.2.4 on 2025-07-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_trades_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='trades',
            name='trade_is_won',
            field=models.BooleanField(null=True),
        ),
    ]
