# Generated by Django 5.2.4 on 2025-07-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_trades_trade_is_won'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
