# Generated by Django 5.2.4 on 2025-07-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_alter_accounts_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trades',
            name='pl',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
