# Generated by Django 5.2.4 on 2025-07-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_alter_trades_pl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradesteps',
            old_name='market_price',
            new_name='current_market_price',
        ),
        migrations.AddField(
            model_name='tradesteps',
            name='pl_if_hit',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='tradesteps',
            name='target_market_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tradesteps',
            name='trade_size_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tradesteps',
            name='trade_size_if_hit',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tradesteps',
            name='current_pl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
