# Generated by Django 5.2.4 on 2025-07-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0006_rename_market_price_tradesteps_current_market_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trades',
            name='scalling_money',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
