# Generated by Django 5.2.4 on 2025-07-29 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0007_trades_scalling_money'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trades',
            old_name='scalling_money',
            new_name='realized_pl',
        ),
    ]
