# Generated by Django 5.2.4 on 2025-07-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0008_rename_scalling_money_trades_realized_pl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trades',
            name='realized_pl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
