# Generated by Django 5.2.4 on 2025-07-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0009_alter_trades_realized_pl'),
    ]

    operations = [
        migrations.AddField(
            model_name='trades',
            name='total_trade_size',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
