# Generated by Django 5.2.4 on 2025-07-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0010_trades_total_trade_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledgernotes',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='ledgernotes',
            name='date_start',
        ),
        migrations.AddField(
            model_name='ledgernotes',
            name='date',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
