# Generated by Django 5.2.4 on 2025-07-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0011_remove_ledgernotes_date_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgernotes',
            name='account_name',
            field=models.CharField(default='All', max_length=25),
            preserve_default=False,
        ),
    ]
