# Generated by Django 5.2.4 on 2025-08-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0014_alter_ledgernotes_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trades',
            name='timeframe',
            field=models.CharField(choices=[('1month', '1month'), ('1week', '1week'), ('1day', '1day'), ('4h', '4h'), ('2h', '2h'), ('1h', '1h'), ('30m', '30m'), ('15m', '15m'), ('5m', '5m')], max_length=10),
        ),
    ]
